export const ERROR_CODES = {
  NOT_FOUND:           'NOT_FOUND',
  UNAUTHORIZED:        'UNAUTHORIZED',
  FORBIDDEN:           'FORBIDDEN',
  RATE_LIMITED:        'RATE_LIMITED',
  VALIDATION_ERROR:    'VALIDATION_ERROR',
  PAYMENT_FAILED:      'PAYMENT_FAILED',
  REPORT_NOT_FOUND:    'REPORT_NOT_FOUND',
  INSUFFICIENT_PLAN:   'INSUFFICIENT_PLAN',
  MISSING_TOKEN:       'MISSING_TOKEN',
  USER_NOT_FOUND:      'USER_NOT_FOUND',
  INTERNAL_ERROR:      'INTERNAL_ERROR',
  SOURCES_UNAVAILABLE: 'SOURCES_UNAVAILABLE',
} as const;
